sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.2
  - 2.1
  - 2.0
before_install: gem install bundler -v 1.14.4
script:
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
branches:
  only:
    - master

